import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/global/Navbar/Navbar";
import SmoothScroll from "@/components/SmoothScroll/SmoothScroll";
import "./globals.css";
import { Check } from "@/components/global/Navbar/Check";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Webrange",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <SmoothScroll> */}
        <main>{children}</main>

        <Check />
        {/* </SmoothScroll> */}
      </body>
    </html>
  );
}
